name: Publish

on:
  push:
    tags:
      - "[0-9]+.[0-9]+.[0-9]+*"

env:
  CARGO_TERM_COLOR: always
  CARGO_REGISTRY_TOKEN: ${{ secrets.CARGO_REGISTRY_TOKEN }}

jobs:
  publish:
    name: Publish to crates.io
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
        with:
          submodules: true
      - uses: dtolnay/rust-toolchain@nightly
      - name: Publish act-types
        run: cargo publish -p act-types
      - name: Publish act-sdk-macros
        run: cargo publish -p act-sdk-macros
      - name: Publish act-sdk
        run: cargo publish -p act-sdk
